---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres-operator-ui
spec:
  chart:
    spec:
      chart: postgres-operator-ui
      version: 1.14.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: postgres-operator-ui-charts
  interval: 1h
  values:
    replicaCount: 1
    resources:
      requests:
        cpu: 10m
        memory: 50M
      limits:
        cpu: 30m
        memory: 100M
    envs:
      operatorClusterNameLabel: "pg-cluster"
      targetNamespace: "databases"
      teams:
        - "mafyuh"
    extraEnvs:
      - name: SPILO_S3_BACKUP_PREFIX
        value: "spilo/"
      - name: AWS_ACCESS_KEY_ID
        value: "K3Bf56zgJk4DqMQnIV2m"
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: postgres-secrets
            key: PG_MINIO_SECRET_KEY
      - name: AWS_DEFAULT_REGION
        value: "us-east-1"
      - name: SPILO_S3_BACKUP_BUCKET
        value: "postgres"
      - name: AWS_ENDPOINT
        value: "https://s3.mafyuh.xyz"
