---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: umami-secrets
spec:
  refreshInterval: 3h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
    - secretKey: APP_SECRET
      remoteRef:
        key: "54efda55-1810-4d90-8794-b2d9004aed56"
    - secretKey: DATABASE_URL
      remoteRef:
        key: "30bb5614-f396-408e-b58b-b3d400024db6"
