apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alloy/
  - arr/
  - authentik/
  - cert-manager/
  - cilium/
  - headlamp/
  - kromgo/
  - loki/
  - longhorn/
  - netbox/
  - nginx/
  - prometheus/
  - reflector/
  - reloader/
  - termix/
  - twingate/