---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  data:
    # Infrastructure
    - secretKey: HOMEPAGE_VAR_UNIFI_TOKEN
      remoteRef:
        key: "e9d80f2d-726a-4bf9-89fb-b3e700364930"
    - secretKey: HOMEPAGE_VAR_TRUENAS_TOKEN
      remoteRef:
        key: "a0e2a2fa-14a0-4391-9d76-b3e70033c518"
    - secretKey: HOMEPAGE_VAR_PROXMOX_TOKEN
      remoteRef:
        key: "b58b92cd-a565-4e9e-a19e-b3e701874d89"
    - secretKey: HOMEPAGE_VAR_PBS_TOKEN
      remoteRef:
        key: "b279b6fd-a11d-44ab-8d35-b3e8002e922b"
    # Media
    - secretKey: HOMEPAGE_VAR_BAZARR_TOKEN
      remoteRef:
        key: "489316a4-8c2f-4fa7-acf9-b25b005e006b"
    - secretKey: HOMEPAGE_VAR_PROWLARR_TOKEN
      remoteRef:
        key: "b38013bc-4caf-4788-8fb2-b25b005d6b02"
    - secretKey: HOMEPAGE_VAR_RADARR_TOKEN
      remoteRef:
        key: "46efe854-cfff-49aa-9403-b25b005b8bb8"
    - secretKey: HOMEPAGE_VAR_SONARR_TOKEN
      remoteRef:
        key: "eb97b60f-f7f1-4f37-b6c9-b258004aca85"
    - secretKey: HOMEPAGE_VAR_LIDARR_TOKEN
      remoteRef:
        key: "bfddd2d0-ba79-47b6-b706-b371017bea28"
    - secretKey: HOMEPAGE_VAR_JELLYFIN_API_KEY
      remoteRef:
        key: "243b914d-d5c4-442e-87ad-b3e70181ee5c"
    - secretKey: HOMEPAGE_VAR_JELLYSEERR_TOKEN
      remoteRef:
        key: "9f3c9356-b984-42a8-aa29-b3e80014f1a7"
    - secretKey: HOMEPAGE_VAR_SABNZBD_API_KEY
      remoteRef:
        key: "76f700af-4d22-4377-991f-b25b005de1b0"
    - secretKey: HOMEPAGE_VAR_AUTHENTIK_TOKEN
      remoteRef:
        key: "6c906ff4-9465-415d-832e-b3e70034a347"
    - secretKey: HOMEPAGE_VAR_GOTIFY_TOKEN
      remoteRef:
        key: "28cc26b9-eb3f-4601-bc2b-b3e80033d288"
    - secretKey: HOMEPAGE_VAR_IMMICH_TOKEN
      remoteRef:
        key: "6b12d46e-4290-4526-a722-b3e70032ca2e"
    # Domains
    - secretKey: PUBLIC_DOMAIN
      remoteRef:
        key: "fa7aa6c7-7c9e-4db1-b5c7-b372002cd0a2"
