---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app homepage
  namespace: &ns default
spec:
  targetNamespace: *ns
  components:
    - ../../../../components/authentik-proxy
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  timeout: 5m
  path: ./kubernetes/apps/default/homepage/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: iac
    namespace: flux-system
  wait: false
  postBuild:
    substitute:
      APP: homepage
    substituteFrom:
      - kind: Secret
        name: homepage-secret
